#
# Copyright (c) 2017, Spreadtrum Communications.
#
# The above copyright notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := sp9863a_14c10_32b
ARCH := arm
ENABLE_THUMB := false
GLOBAL_DEFINES += SPRD_MMU_LPAE

MODULES += \
	app/sprdboot

GLOBAL_DEFINES += \
	KERNEL_ADR=0x80008000UL \
	DT_ADR=0x9df00000UL \
	RAMDISK_ADR=0xa0000000UL \
	LK_BACKUP_FOR_MINIDUMP_ADR=0xad000000 \
	SPRD_BOARD_INFO_ID="sp9863a 14c10 1000"

#boot device
GLOBAL_DEFINES += \
	CONFIG_EMMC_BOOT

# I2C
SPRD_I2C_HW_SUPPORT:=1

# CHARGER
SPRD_CHARGER_FAN54015_SUPPORT:=1
GLOBAL_DEFINES += SPRDCHG_I2C_BUS=4

# GPIO
SPRD_GPIO_PLUS_SUPPORT:=1

# KEYPAD
GLOBAL_DEFINES += SPRD_VOLUMEDOWN_GPIO=124

# DVFS
CONFIG_DVFS_ADDR_VALUE := 0x60
CONFIG_DVFS_TX_REG_ADDR_VALUE := 0x0
CONFIG_DVFS_RX_REG_ADDR_VALUE := 0x0
GLOBAL_DEFINES += \
	CONFIG_DVFS_ADDR=$(CONFIG_DVFS_ADDR_VALUE) \
	CONFIG_DVFS_TX_REG_ADDR=$(CONFIG_DVFS_TX_REG_ADDR_VALUE) \
	CONFIG_DVFS_RX_REG_ADDR=$(CONFIG_DVFS_RX_REG_ADDR_VALUE)

# sensorhub
#SPRD_SENSOR_HUB_LK:=1

# coresight_etb_dump
SPRD_ETB_DUMP_LK:=1

# CP
SPRD_LTE_SUPPORT := 1

# attach lcd
LCD_NT36525B_TM_MIPI_HDP := 1
LCD_NT36525B_HX_MIPI_HDP := 1

# lcd power supply config
GLOBAL_DEFINES += \
	CONFIG_SPLASH_SCREEN \
	CONFIG_LCM_GPIO_RSTN=50 \
	CONFIG_LCM_GPIO_AVDDEN=4 \
	CONFIG_LCM_GPIO_AVEEEN=5

# define get ntc vol api
GLOBAL_DEFINES += \
	CONFIG_NTC_VOL=1 \
	NTC_VOL_CH=4 \
	NTC_VOL_SCALE=0 \
	NTC_VOL_MUX=0 \
	NTC_VOL_CAL_TYPE=2

# define the voltage(mv) corresponding to 0,55,65 degrees
GLOBAL_DEFINES += \
	VOL2TEMP_DISCHARGING_LOW=1862 \
	VOL2TEMP_DISCHARGING_HIGH=574 \
	VOL2TEMP_DISBOOTING=464

#secboot openssl
# ENABLE_SECBOOT_OPENSSL:=1

# enable gicv3
# ENABLE_SPRD_GICV3:=true

# support log storage
SPRD_LOG_SUPPORT := 1

#support trace(not coexit with SPRD_LOG_SUPPORT)
SPRD_TRACE_SUPPORT := 0

# Match DTBO by BoardID
SPRD_DTBO_BOARDID := 0

# enable Serror panic in LK
ENABLE_ASYNC_SUPPORT:=true

# 7S reset config
# CONFIG_7S_RST_MODULE_EN	//0:disable module; 1:enable module
# CONFIG_7S_RST_SW_MODE		//0:hw reset,1:arm reset,power keep on	//hard for user version
# CONFIG_7S_RST_SHORT_MODE	//0:long press then release key to trigger;1:press key some time to trigger
# CONFIG_7S_RST_2KEY_MODE	//0:1Key--Normal mode; 1:2KEY
# CONFIG_7S_RST_THRESHOLD	//7S, hold key down for this time to trigger
#

GLOBAL_DEFINES += \
	CONFIG_7S_RST_SW_MODE=1 \
	CONFIG_7S_RST_MODULE_EN=1 \
	CONFIG_7S_RST_SHORT_MODE=1 \
	CONFIG_7S_RST_2KEY_MODE=1 \
	CONFIG_7S_RST_THRESHOLD=7
