#
# Copyright (c) 2017, Spreadtrum Communications.
#
# The above copyright notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := sp9863a_1h10_go
ARCH := arm64
WITH_SMP := 1

MODULES += \
	app/sprdboot

GLOBAL_DEFINES += \
	KERNEL_ADR=0x80080000UL \
	DT_ADR=0x9df00000UL \
	RAMDISK_ADR=0xa0000000UL \
	LK_BACKUP_FOR_MINIDUMP_ADR=0xad000000 \
	SPRD_BOARD_INFO_ID="sp9863a 1h10 go"
#modified by klijuan for NYX-4423 Additional validation for hardcoded SP level
include $(shell pwd)/../../tools/secureboot_key/config/version.cfg
GLOBAL_DEFINES += \
	ANTIROLLBACK_HW=\"$(trusted_version)\"
export ANTIROLLBACK_HW
GLOBAL_DEFINES += \
	ANTIROLLBACK_VBMETA=\"$(avb_version_vbmeta)\"
export ANTIROLLBACK_VBMETA
GLOBAL_DEFINES += \
	ANTIROLLBACK_VBMETA_SYSTEM=\"$(avb_version_system)\"
export ANTIROLLBACK_VBMETA_SYSTEM
$(warning ANTIROLLBACK_HW=$(ANTIROLLBACK_HW))
$(warning ANTIROLLBACK_VBMETA=$(ANTIROLLBACK_VBMETA))
$(warning ANTIROLLBACK_VBMETA_SYSTEM=$(ANTIROLLBACK_VBMETA_SYSTEM))
#boot device
GLOBAL_DEFINES += \
	CONFIG_EMMC_BOOT

# enable LK dtb
#GLOBAL_DEFINES += \
	CONFIG_DTS_MEM_LAYOUT \
	CONFIG_OF_CONTROL

# I2C
SPRD_I2C_HW_SUPPORT:=1

# CHARGER
GLOBAL_DEFINES += SPRDCHG_I2C_BUS=4

# GPIO
SPRD_GPIO_PLUS_SUPPORT:=1

# KEYPAD
GLOBAL_DEFINES += SPRD_VOLUMEKEY_EIC=2

# DVFS
CONFIG_DVFS_ADDR_VALUE := 0x60
CONFIG_DVFS_TX_REG_ADDR_VALUE := 0x0
CONFIG_DVFS_RX_REG_ADDR_VALUE := 0x0
GLOBAL_DEFINES += \
	CONFIG_DVFS_ADDR=$(CONFIG_DVFS_ADDR_VALUE) \
	CONFIG_DVFS_TX_REG_ADDR=$(CONFIG_DVFS_TX_REG_ADDR_VALUE) \
	CONFIG_DVFS_RX_REG_ADDR=$(CONFIG_DVFS_RX_REG_ADDR_VALUE)

# sensorhub
#SPRD_SENSOR_HUB_LK:=1

# coresight_etb_dump
SPRD_ETB_DUMP_LK:=1

# CP
SPRD_LTE_SUPPORT := 1

# misdata
GLOBAL_DEFINES += \
	MISCDATA_ADDRESS_BASE=10496 \
	MISCDATA_MAGIC_OFFSET=0 \
	MISCDATA_MAGIC_SIZE=4 \
	MISCDATA_RTC_TIME_OFFSET=4 \
	MISCDATA_RTC_TIME_SIZE=8 \
	MISCDATA_CHARGE_CYCLE_OFFSET=12 \
	MISCDATA_CHARGE_CYCLE_SIZE=4 \
	MISCDATA_BASP_OFFSET=16 \
	MISCDATA_BASP_SIZE=4 \
	MISCDATA_CAPACITY_OFFSET=20 \
	MISCDATA_CAPACITY_SIZE=4 \
	MISCDATA_CAPACITY_CHECK_OFFSET=24 \
	MISCDATA_CAPACITY_CHECK_SIZE=4 \
	MISCDATA_SHUTDOWN_CHARGE_FLAG_OFFSET=28 \
	MISCDATA_SHUTDOWN_CHARGE_FLAG_SIZE=4 \
	MISCDATA_AUTO_POWERON_FLAG_OFFSET=32 \
	MISCDATA_AUTO_POWERON_FLAG_SIZE=1 \
	MISCDATA_SHUTDOWN_CHARGE_EIGHTY_PERCENTAGE_STOP_CHARGE_OFFSET=33 \
	MISCDATA_SHUTDOWN_CHARGE_EIGHTY_PERCENTAGE_STOP_CHARGE_SIZE=1

# attach lcd
LCD_NT35596_BOE_MIPI_FHD := 1
LCD_NT35532_TRULY_MIPI_FHD := 1
LCD_NT35695_TRULY_MIPI_FHD := 1

# lcd power supply config
GLOBAL_DEFINES += \
	CONFIG_SPLASH_SCREEN \
	POWEROFF_CHARGE_LOGO_SUPPORT=1 \
	CONFIG_LCM_GPIO_RSTN=50 \
	CONFIG_LCM_GPIO_AVDDEN=89 

# define get ntc vol api  fixed:?????
GLOBAL_DEFINES += \
	CONFIG_NTC_VOL=1 \
	NTC_VOL_CH=0 \
	NTC_VOL_SCALE=0 \
	NTC_VOL_MUX=0 \
	NTC_VOL_CAL_TYPE=2

# define the voltage(mv) corresponding to 0,55,65 degrees
GLOBAL_DEFINES += \
	VOL2TEMP_DISCHARGING_LOW=687 \
	VOL2TEMP_DISCHARGING_HIGH=131 \
	VOL2TEMP_DISBOOTING=97

#secboot openssl
# ENABLE_SECBOOT_OPENSSL:=1

#enable DDR boot
# ENABLE_DDR_BOOT:=1

# enable gicv3
# ENABLE_SPRD_GICV3:=true

# support log storage
SPRD_LOG_SUPPORT := 1

#support trace(not coexit with SPRD_LOG_SUPPORT)
SPRD_TRACE_SUPPORT := 0

# Match DTBO by BoardID
SPRD_DTBO_BOARDID := 0x190000

# enable Serror panic in LK
ENABLE_ASYNC_SUPPORT:=true

# 7S reset config
# CONFIG_7S_RST_MODULE_EN	//0:disable module; 1:enable module
# CONFIG_7S_RST_SW_MODE		//0:hw reset,1:arm reset,power keep on	//hard for user version
# CONFIG_7S_RST_SHORT_MODE	//0:long press then release key to trigger;1:press key some time to trigger
# CONFIG_7S_RST_2KEY_MODE	//0:1Key--Normal mode; 1:2KEY
# CONFIG_7S_RST_THRESHOLD	//7S, hold key down for this time to trigger
#

GLOBAL_DEFINES += \
	CONFIG_7S_RST_SW_MODE=1 \
	CONFIG_7S_RST_MODULE_EN=1 \
	CONFIG_7S_RST_SHORT_MODE=1 \
	CONFIG_7S_RST_2KEY_MODE=0 \
	CONFIG_7S_RST_THRESHOLD=15

#add by jinqiang @20241106 
GLOBAL_DEFINES += \
	CONFIG_ERASE_SPL_AUTO_DOWNLOAD
	
CONFIG_UDC := 1
CONFIG_UDC_LCD_MIPI :=1
GLOBAL_DEFINES += CONFIG_UDC_SHARKL3
SPRD_CHARGER_AW32257_SUPPORT:=1
GLOBAL_DEFINES += CONFIG_DL_PCTOOL_AUTHORIZE