#
# Copyright (c) 2017, Spreadtrum Communications.
#
# The above copyright notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := ums512_25c10
ARCH := arm64

MODULES += \
	app/sprdboot

GLOBAL_DEFINES += \
	KERNEL_ADR=0x80080000UL \
	DT_ADR=0x83f00000UL \
	RAMDISK_ADR=0xa0000000UL \
	LK_BACKUP_FOR_MINIDUMP_ADR=0xae000000 \
	SPRD_BOARD_INFO_ID="ums512 25c10 1000"

#boot device
GLOBAL_DEFINES += \
	CONFIG_EMMC_BOOT

# sc27xx vibrator
GLOBAL_DEFINES += \
	CONFIG_SC27XX_VDDVIB_VSD2

# I2C
SPRD_I2C_HW_SUPPORT:=1

# CHARGER
SPRD_CHARGER_BQ25890_SUPPORT:=1
SPRD_CHARGER_SGM4154X_SUPPORT:=1
SPRD_CHARGER_SY6970_SUPPORT:=1
GLOBAL_DEFINES += SPRDCHG_I2C_BUS=4

# GPIO
SPRD_GPIO_SUPPORT:=1

# KEYPAD
GLOBAL_DEFINES += SPRD_VOLUMEUP_GPIO=125

# DVFS
CONFIG_DVFS_ADDR_VALUE := 0x60
CONFIG_DVFS_TX_REG_ADDR_VALUE := 0x2
CONFIG_DVFS_RX_REG_ADDR_VALUE := 0x0

GLOBAL_DEFINES += \
	CONFIG_DVFS_ADDR=$(CONFIG_DVFS_ADDR_VALUE) \
	CINFIG_DVFS_TX_5_REG_ADDR=$(CONFIG_DVFS_TX_REG_ADDR_VALUE) \
	CINFIG_DVFS_TX_7_REG_ADDR=$(CONFIG_DVFS_RX_REG_ADDR_VALUE)

# sensorhub
SPRD_SENSOR_HUB_LK:=1

# coresight_etb_dump
SPRD_ETB_DUMP_LK:=1

# CP
SPRD_LTE_SUPPORT := 1
SPRD_AGDSP_SUPPORT := 1

# low power
GLOBAL_DEFINES += \
	CONFIG_SUPPORT_LOWPOWER \
	CONFIG_AON_LPC_EN \
	CONFIG_AP_LPC_EN \
	CONFIG_CLOCK_AUTO_GATE_EN \
	CONFIG_DCDCCORE_DEEP_DROP_EN=1 \
	CONFIG_DCDCCORE_DEEP_DROP_VOL=600 \
	CONFIG_DCDCSRAM_DEEP_DROP_EN=1 \
	CONFIG_DCDCSRAM_DEEP_DROP_VOL=700 \
	CONFIG_DCDCMODEM_DEEP_DROP_EN=1 \
	CONFIG_DCDCMODEM_DEEP_DROP_VOL=700 \
	CONFIG_DCDCGPU_DEEP_DROP_EN=1 \
	CONFIG_DCDCGPU_DEEP_DROP_VOL=550

# attach lcd
LCD_HX83102E_XY_HSD_MIPI_HDP := 1
# lcd power supply config
GLOBAL_DEFINES += \
	CONFIG_SPLASH_SCREEN \
	CONFIG_LCM_GPIO_RSTN=50 \
	CONFIG_LCM_GPIO_AVDDEN=138 \
	CONFIG_LCM_GPIO_AVEEEN=139

# customer requirements
CUSTOMER_PHONE := 1

# enable gicv3
# ENABLE_SPRD_GICV3:=true

# support log storage
SPRD_LOG_SUPPORT := 1
#support trace(not coexit with SPRD_LOG_SUPPORT)
SPRD_TRACE_SUPPORT := 0

# 7S reset config
# CONFIG_7S_RST_MODULE_EN	//0:disable module; 1:enable module
# CONFIG_7S_RST_SW_MODE		//0:hw reset,1:arm reset,power keep on	//hard for user version
# CONFIG_7S_RST_SHORT_MODE	//0:long press then release key to trigger;1:press key some time to trigger
# CONFIG_7S_RST_2KEY_MODE	//0:1Key--Normal mode; 1:2KEY
# CONFIG_7S_RST_THRESHOLD	//7S, hold key down for this time to trigger
#

GLOBAL_DEFINES += \
	CONFIG_7S_RST_SW_MODE=1 \
	CONFIG_7S_RST_MODULE_EN=1 \
	CONFIG_7S_RST_SHORT_MODE=1 \
	CONFIG_7S_RST_2KEY_MODE=1 \
	CONFIG_7S_RST_THRESHOLD=7
