#
# Copyright (c) 2017, Spreadtrum Communications.
#
# The above copyright notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

LOCAL_DIR := $(GET_LOCAL_DIR)

TARGET := ums9620_1h10
ARCH := arm64
WITH_SMP := 1

MODULES += \
	app/sprdboot

GLOBAL_DEFINES += \
	KERNEL_ADR=0x80080000UL \
	DT_ADR=0xbbf00000UL \
	RAMDISK_ADR=0xd0000000UL \
	SPRD_BOARD_INFO_ID="ums9620 1h10 1000"

#boot device
GLOBAL_DEFINES += \
	SPRD_EMMC_BOOTDEVICE='"androidboot.boot_devices=soc/soc:ap-ahb/22200000.sdio"' \
	SPRD_UFS_BOOTDEVICE='"androidboot.boot_devices=soc/soc:ap-ahb/22000000.ufs"' \
	CONFIG_UFS_DTS_PATH='"/soc/ap-ahb/ufs"' \
	CONFIG_EMMC_DTS_PATH='"/soc/ap-ahb/sdio@22200000"' \
	SPRD_SEND_STORAGE_TYPE \
	CONFIG_BLK_DEV_BOOT

# I2C
SPRD_I2C_HW_SUPPORT:=0

# CHARGER
SPRD_CHARGER_BQ2560X_SUPPORT:=1
GLOBAL_DEFINES += SPRDCHG_I2C_BUS=6

# GPIO
SPRD_GPIO_SUPPORT:=1
# KEYPAD
GLOBAL_DEFINES += SPRD_VOLUMEDOWN_GPIO=7
# sensorhub
#SPRD_SENSOR_HUB_LK:=1
# coresight_etb_dump
SPRD_ETB_DUMP_LK:=1

# DVFS
#CONFIG_DVFS_ADDR_VALUE := 0x60
#CONFIG_DVFS_TX_REG_ADDR_VALUE := 0x2
#CONFIG_DVFS_RX_REG_ADDR_VALUE := 0x0
#GLOBAL_DEFINES += \
#	CONFIG_DVFS_ADDR=$(CONFIG_DVFS_ADDR_VALUE) \
#	CINFIG_DVFS_TX_0_REG_ADDR=$(CONFIG_DVFS_TX_REG_ADDR_VALUE) \
#	CINFIG_DVFS_TX_1_REG_ADDR=$(CONFIG_DVFS_RX_REG_ADDR_VALUE)

# CP
SPRD_LTE_SUPPORT := 0
SPRD_AGDSP_SUPPORT := 1
LTE_AGDSP_ADDR := 0xAFA00000
LTE_AGDSP_SIZE := 0x00600000

GLOBAL_DEFINES += \
	HEADER_SIZE=0x80 \
	DFS_ADDR=0x62800000 \
	DFS_SIZE=0x10000

# misdata
GLOBAL_DEFINES += \
	MISCDATA_ADDRESS_BASE=10496 \
	MISCDATA_MAGIC_OFFSET=0 \
	MISCDATA_MAGIC_SIZE=4 \
	MISCDATA_RTC_TIME_OFFSET=4 \
	MISCDATA_RTC_TIME_SIZE=8 \
	MISCDATA_CHARGE_CYCLE_OFFSET=12 \
	MISCDATA_CHARGE_CYCLE_SIZE=4 \
	MISCDATA_BASP_OFFSET=16 \
	MISCDATA_BASP_SIZE=4 \
	MISCDATA_CAPACITY_OFFSET=20 \
	MISCDATA_CAPACITY_SIZE=4 \
	MISCDATA_CAPACITY_CHECK_OFFSET=24 \
	MISCDATA_CAPACITY_CHECK_SIZE=4 \
	MISCDATA_SHUTDOWN_CHARGE_FLAG_OFFSET=28 \
	MISCDATA_SHUTDOWN_CHARGE_FLAG_SIZE=4 \
	MISCDATA_AUTO_POWERON_FLAG_OFFSET=32 \
	MISCDATA_AUTO_POWERON_FLAG_SIZE=1

# attach lcd
LCD_G40396_TRULY_MIPI_FHD := 1
LCD_NT36672E_TRULY_MIPI_FHD := 1
AMOLED_G2667FP108FF_VISIONOX_MIPI_FHD := 1

# lcd power supply config
GLOBAL_DEFINES += \
	CONFIG_SPLASH_SCREEN \
	POWEROFF_CHARGE_LOGO_SUPPORT=1 \
	CONFIG_LCM_GPIO_RSTN=11 \
	CONFIG_LCM_GPIO_AVDDEN=192 \
	CONFIG_LCM_GPIO_AVEEEN=191

# define charging current of low voltage precharge
GLOBAL_DEFINES += \
	PRE_CHG_CUR=360

# define get ntc vol api
GLOBAL_DEFINES += \
	CONFIG_NTC_VOL=1 \
	NTC_VOL_CH=0 \
	NTC_VOL_SCALE=1 \
	NTC_VOL_MUX=0 \
	NTC_VOL_CAL_TYPE=2

# define the voltage(mv) corresponding to 0,55,65 degrees
GLOBAL_DEFINES += \
	VOL2TEMP_DISCHARGING_LOW=668 \
	VOL2TEMP_DISCHARGING_HIGH=125 \
	VOL2TEMP_DISBOOTING=93

#secboot openssl
# ENABLE_SECBOOT_OPENSSL:=1

#enable DDR boot
# ENABLE_DDR_BOOT:=1

# enable gicv3
# ENABLE_SPRD_GICV3:=true

# support log storage
SPRD_LOG_SUPPORT := 1

#support trace(not coexit with SPRD_LOG_SUPPORT)
SPRD_TRACE_SUPPORT := 0

#RPMB
SPRD_RPMB_SUPPORT:=1

# enable Serror panic in LK
ENABLE_ASYNC_SUPPORT:=true

# usbpinmux config
GLOBAL_DEFINES += \
	CONFIG_USBPINMUX

# Match DTBO by BoardID
SPRD_DTBO_BOARDID := 0x110000

# 7S reset config
# CONFIG_7S_RST_MODULE_EN	//0:disable module; 1:enable module
# CONFIG_7S_RST_SW_MODE		//0:hw reset,1:arm reset,power keep on	//hard for user version
# CONFIG_7S_RST_SHORT_MODE	//0:long press then release key to trigger;1:press key some time to trigger
# CONFIG_7S_RST_2KEY_MODE	//0:1Key--Normal mode; 1:2KEY
# CONFIG_7S_RST_THRESHOLD	//7S, hold key down for this time to trigger
#

GLOBAL_DEFINES += \
	CONFIG_7S_RST_SW_MODE=1 \
	CONFIG_7S_RST_MODULE_EN=1 \
	CONFIG_7S_RST_SHORT_MODE=1 \
	CONFIG_7S_RST_2KEY_MODE=1 \
	CONFIG_7S_RST_THRESHOLD=7

# Enable soc dump
SPRD_SOC_DUMP_SUPPORT:=0
