

#define ZCFG_USERDEBUG_LOCKDEVICE_CANNOT_BOOT
#define ZCFG_SN_EMPTY_CANNOT_BOOT
//#define ZCFG_DISABLE_DOWNLOAD
#define CONFIG_EMMC_WP
//#define CONFIG_CALI_MODE
//#define ZCFG_ENABLE_FDL_DOWNLOAD_AUTH
#define ZCFG_BACKLIGHT_DELAY 150
#define CONFIG_TEST_FLAG
#define ZCFG_HMD_ENTERPRISE_API
#define CONFIG_HMD_FASTBOOT
#define ZCFG_CMD_CHARGE_MODE
#define ZCFG_BACKLIGHT_BOOST_MODE
#define ZCFG_KEYMAP_VALUE_UNSUPPORT_F11
#define ZCFG_LK_KEY_VOLUMEDOWN_CUST
#define ZCFG_UBOOT_BACKLIGHT_ON_LEVEL 102
#define ZCFG_UBOOT_IBAT_CUR 1000
#define ZCFG_SHUTDOWN_CHARGE_EIGHTY_PERCENTAGE_STOP_CHARGE
#define ZCFG_BATTERY_PROTECTION_POWER_LIMIT_PRIORITY_OVER_THERMAL
#define ZCFG_ENABLE_CHARGE_CURRENT_TERMINATION
#ifndef __BOARD_H
#define __BOARD_H

#define ZCFG_ACC_MC3416P_POSTION 4
#define ZCFG_ACC_STK83XX_POSTION 4
#define ZCFG_ACC_MXC4005_POSTION 4
#define ZCFG_ACC_MIR3DA_POSTION 5
#define ZCFG_TSX_32KLESS
#define ZCFG_MK_CHAR_EN_ONLY_USE_GPIO
//#define ZCFG_LIGHT_CALI_VALUE_EIGHT_HUNDRED_LUX

#endif


#define ZCFG_LCM_WIDTH 576
#define ZCFG_LCM_HEIGHT 1280
/*----Add zyt.h - Please #include <soc/sprd/board.h> ----*/

#define ZCFG_USERDEBUG_LOCKDEVICE_CANNOT_BOOT
#define ZCFG_SN_EMPTY_CANNOT_BOOT
//#define ZCFG_DISABLE_DOWNLOAD
#define CONFIG_EMMC_WP
//#define CONFIG_CALI_MODE
//#define ZCFG_ENABLE_FDL_DOWNLOAD_AUTH
#define ZCFG_BACKLIGHT_DELAY 150

#define ZCFG_USERDEBUG_LOCKDEVICE_CANNOT_BOOT
#define ZCFG_SN_EMPTY_CANNOT_BOOT
//#define ZCFG_DISABLE_DOWNLOAD
#define CONFIG_EMMC_WP
//#define CONFIG_CALI_MODE
//#define ZCFG_ENABLE_FDL_DOWNLOAD_AUTH
#define ZCFG_BACKLIGHT_DELAY 150
/*------customer.h define below------------------------------*/

#define CONFIG_TEST_FLAG
#define ZCFG_HMD_ENTERPRISE_API
#define CONFIG_HMD_FASTBOOT
#define ZCFG_CMD_CHARGE_MODE
#define ZCFG_BACKLIGHT_BOOST_MODE
#define ZCFG_KEYMAP_VALUE_UNSUPPORT_F11
#define ZCFG_LK_KEY_VOLUMEDOWN_CUST
#define ZCFG_UBOOT_BACKLIGHT_ON_LEVEL 102
#define ZCFG_UBOOT_IBAT_CUR 1000
#define ZCFG_SHUTDOWN_CHARGE_EIGHTY_PERCENTAGE_STOP_CHARGE
#define ZCFG_BATTERY_PROTECTION_POWER_LIMIT_PRIORITY_OVER_THERMAL
#define ZCFG_ENABLE_CHARGE_CURRENT_TERMINATION
#define CONFIG_TEST_FLAG
#define ZCFG_HMD_ENTERPRISE_API
#define CONFIG_HMD_FASTBOOT
#define ZCFG_CMD_CHARGE_MODE
#define ZCFG_BACKLIGHT_BOOST_MODE
#define ZCFG_KEYMAP_VALUE_UNSUPPORT_F11
#define ZCFG_LK_KEY_VOLUMEDOWN_CUST
#define ZCFG_UBOOT_BACKLIGHT_ON_LEVEL 102
#define ZCFG_UBOOT_IBAT_CUR 1000
#define ZCFG_SHUTDOWN_CHARGE_EIGHTY_PERCENTAGE_STOP_CHARGE
#define ZCFG_BATTERY_PROTECTION_POWER_LIMIT_PRIORITY_OVER_THERMAL
#define ZCFG_ENABLE_CHARGE_CURRENT_TERMINATION
#define ZCFG_HMD_CLOSE_UART_JTAG
#define HIGH_BATTERY_VOLTAGE_SUPPORT
#define ZCFG_AUDIO_EXTERNAL_K_CLASS_SUPPORT