/*
 *  <adf_format.c> - <adf format>
 *
 *  Copyright (C) 2019 Unisoc Communications Inc.
 *  History:
 *      <2021-08-09> <pony.wu@unisoc.com>
 *
 *      The above copyright notice shall be
 *      included in all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *      IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *      CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 *      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 *      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

//#include <common.h>
//#include <linux/types.h>
#include "drm_fourcc.h"
#include "adf_format.h"

#ifndef bool
typedef int bool;
#endif
#ifndef false
#define false 0
#endif
#ifndef true
#define true 1
#endif

//#define pr_debug(fmt, args...) do { } while (0)

bool adf_format_is_standard(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_C8:
	case SPRD_DRM_FORMAT_RGB332:
	case SPRD_DRM_FORMAT_BGR233:
	case SPRD_DRM_FORMAT_XRGB4444:
	case SPRD_DRM_FORMAT_XBGR4444:
	case SPRD_DRM_FORMAT_RGBX4444:
	case SPRD_DRM_FORMAT_BGRX4444:
	case SPRD_DRM_FORMAT_ARGB4444:
	case SPRD_DRM_FORMAT_ABGR4444:
	case SPRD_DRM_FORMAT_RGBA4444:
	case SPRD_DRM_FORMAT_BGRA4444:
	case SPRD_DRM_FORMAT_XRGB1555:
	case SPRD_DRM_FORMAT_XBGR1555:
	case SPRD_DRM_FORMAT_RGBX5551:
	case SPRD_DRM_FORMAT_BGRX5551:
	case SPRD_DRM_FORMAT_ARGB1555:
	case SPRD_DRM_FORMAT_ABGR1555:
	case SPRD_DRM_FORMAT_RGBA5551:
	case SPRD_DRM_FORMAT_BGRA5551:
	case SPRD_DRM_FORMAT_RGB565:
	case SPRD_DRM_FORMAT_BGR565:
	case SPRD_DRM_FORMAT_RGB888:
	case SPRD_DRM_FORMAT_BGR888:
	case SPRD_DRM_FORMAT_XRGB8888:
	case SPRD_DRM_FORMAT_XBGR8888:
	case SPRD_DRM_FORMAT_RGBX8888:
	case SPRD_DRM_FORMAT_BGRX8888:
	case SPRD_DRM_FORMAT_ARGB8888:
	case SPRD_DRM_FORMAT_ABGR8888:
	case SPRD_DRM_FORMAT_RGBA8888:
	case SPRD_DRM_FORMAT_BGRA8888:
	case SPRD_DRM_FORMAT_XRGB2101010:
	case SPRD_DRM_FORMAT_XBGR2101010:
	case SPRD_DRM_FORMAT_RGBX1010102:
	case SPRD_DRM_FORMAT_BGRX1010102:
	case SPRD_DRM_FORMAT_ARGB2101010:
	case SPRD_DRM_FORMAT_ABGR2101010:
	case SPRD_DRM_FORMAT_RGBA1010102:
	case SPRD_DRM_FORMAT_BGRA1010102:
	case SPRD_DRM_FORMAT_YUYV:
	case SPRD_DRM_FORMAT_YVYU:
	case SPRD_DRM_FORMAT_UYVY:
	case SPRD_DRM_FORMAT_VYUY:
	case SPRD_DRM_FORMAT_AYUV:
	case SPRD_DRM_FORMAT_NV12:
	case SPRD_DRM_FORMAT_NV21:
	case SPRD_DRM_FORMAT_NV16:
	case SPRD_DRM_FORMAT_NV61:
	case SPRD_DRM_FORMAT_YUV410:
	case SPRD_DRM_FORMAT_YVU410:
	case SPRD_DRM_FORMAT_YUV411:
	case SPRD_DRM_FORMAT_YVU411:
	case SPRD_DRM_FORMAT_YUV420:
	case SPRD_DRM_FORMAT_YVU420:
	case SPRD_DRM_FORMAT_YUV422:
	case SPRD_DRM_FORMAT_YVU422:
	case SPRD_DRM_FORMAT_YUV444:
	case SPRD_DRM_FORMAT_YVU444:
		return true;
	default:
		return false;
	}
}

bool adf_format_is_rgb(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_C8:
	case SPRD_DRM_FORMAT_RGB332:
	case SPRD_DRM_FORMAT_BGR233:
	case SPRD_DRM_FORMAT_XRGB1555:
	case SPRD_DRM_FORMAT_XBGR1555:
	case SPRD_DRM_FORMAT_RGBX5551:
	case SPRD_DRM_FORMAT_BGRX5551:
	case SPRD_DRM_FORMAT_ARGB1555:
	case SPRD_DRM_FORMAT_ABGR1555:
	case SPRD_DRM_FORMAT_RGBA5551:
	case SPRD_DRM_FORMAT_BGRA5551:
	case SPRD_DRM_FORMAT_RGB565:
	case SPRD_DRM_FORMAT_BGR565:
	case SPRD_DRM_FORMAT_RGB888:
	case SPRD_DRM_FORMAT_BGR888:
	case SPRD_DRM_FORMAT_XRGB8888:
	case SPRD_DRM_FORMAT_XBGR8888:
	case SPRD_DRM_FORMAT_RGBX8888:
	case SPRD_DRM_FORMAT_BGRX8888:
	case SPRD_DRM_FORMAT_XRGB2101010:
	case SPRD_DRM_FORMAT_XBGR2101010:
	case SPRD_DRM_FORMAT_RGBX1010102:
	case SPRD_DRM_FORMAT_BGRX1010102:
	case SPRD_DRM_FORMAT_ARGB2101010:
	case SPRD_DRM_FORMAT_ABGR2101010:
	case SPRD_DRM_FORMAT_RGBA1010102:
	case SPRD_DRM_FORMAT_BGRA1010102:
	case SPRD_DRM_FORMAT_ARGB8888:
	case SPRD_DRM_FORMAT_ABGR8888:
	case SPRD_DRM_FORMAT_RGBA8888:
	case SPRD_DRM_FORMAT_BGRA8888:
		return true;

	default:
		return false;
	}
}

u8 adf_format_num_planes(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_YUV410:
	case SPRD_DRM_FORMAT_YVU410:
	case SPRD_DRM_FORMAT_YUV411:
	case SPRD_DRM_FORMAT_YVU411:
	case SPRD_DRM_FORMAT_YUV420:
	case SPRD_DRM_FORMAT_YVU420:
	case SPRD_DRM_FORMAT_YUV422:
	case SPRD_DRM_FORMAT_YVU422:
	case SPRD_DRM_FORMAT_YUV444:
	case SPRD_DRM_FORMAT_YVU444:
		return 3;
	case SPRD_DRM_FORMAT_NV12:
	case SPRD_DRM_FORMAT_NV21:
	case SPRD_DRM_FORMAT_NV16:
	case SPRD_DRM_FORMAT_NV61:
		return 2;
	default:
		return 1;
	}
}

u8 adf_format_bpp(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_C8:
	case SPRD_DRM_FORMAT_RGB332:
	case SPRD_DRM_FORMAT_BGR233:
		return 8;

	case SPRD_DRM_FORMAT_XRGB1555:
	case SPRD_DRM_FORMAT_XBGR1555:
	case SPRD_DRM_FORMAT_RGBX5551:
	case SPRD_DRM_FORMAT_BGRX5551:
	case SPRD_DRM_FORMAT_ARGB1555:
	case SPRD_DRM_FORMAT_ABGR1555:
	case SPRD_DRM_FORMAT_RGBA5551:
	case SPRD_DRM_FORMAT_BGRA5551:
	case SPRD_DRM_FORMAT_RGB565:
	case SPRD_DRM_FORMAT_BGR565:
		return 16;

	case SPRD_DRM_FORMAT_RGB888:
	case SPRD_DRM_FORMAT_BGR888:
		return 24;

	case SPRD_DRM_FORMAT_XRGB8888:
	case SPRD_DRM_FORMAT_XBGR8888:
	case SPRD_DRM_FORMAT_RGBX8888:
	case SPRD_DRM_FORMAT_BGRX8888:
	case SPRD_DRM_FORMAT_XRGB2101010:
	case SPRD_DRM_FORMAT_XBGR2101010:
	case SPRD_DRM_FORMAT_RGBX1010102:
	case SPRD_DRM_FORMAT_BGRX1010102:
	case SPRD_DRM_FORMAT_ARGB2101010:
	case SPRD_DRM_FORMAT_ABGR2101010:
	case SPRD_DRM_FORMAT_RGBA1010102:
	case SPRD_DRM_FORMAT_BGRA1010102:
	case SPRD_DRM_FORMAT_ARGB8888:
	case SPRD_DRM_FORMAT_ABGR8888:
	case SPRD_DRM_FORMAT_RGBA8888:
	case SPRD_DRM_FORMAT_BGRA8888:
		return 32;

	default:
		//pr_debug("%s: unsupported pixel format %u\n", __func__, format);
		return 0;
	}
}

u8 adf_format_plane_cpp(u32 format, int plane)
{
	if (plane >= adf_format_num_planes(format))
		return 0;

	switch (format) {
	case SPRD_DRM_FORMAT_YUYV:
	case SPRD_DRM_FORMAT_YVYU:
	case SPRD_DRM_FORMAT_UYVY:
	case SPRD_DRM_FORMAT_VYUY:
		return 2;
	case SPRD_DRM_FORMAT_NV12:
	case SPRD_DRM_FORMAT_NV21:
	case SPRD_DRM_FORMAT_NV16:
	case SPRD_DRM_FORMAT_NV61:
		return plane ? 2 : 1;
	case SPRD_DRM_FORMAT_YUV410:
	case SPRD_DRM_FORMAT_YVU410:
	case SPRD_DRM_FORMAT_YUV411:
	case SPRD_DRM_FORMAT_YVU411:
	case SPRD_DRM_FORMAT_YUV420:
	case SPRD_DRM_FORMAT_YVU420:
	case SPRD_DRM_FORMAT_YUV422:
	case SPRD_DRM_FORMAT_YVU422:
	case SPRD_DRM_FORMAT_YUV444:
	case SPRD_DRM_FORMAT_YVU444:
		return 1;
	default:
		return adf_format_bpp(format) / 8;
	}
}

u8 adf_format_horz_chroma_subsampling(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_YUV411:
	case SPRD_DRM_FORMAT_YVU411:
	case SPRD_DRM_FORMAT_YUV410:
	case SPRD_DRM_FORMAT_YVU410:
		return 4;
	case SPRD_DRM_FORMAT_YUYV:
	case SPRD_DRM_FORMAT_YVYU:
	case SPRD_DRM_FORMAT_UYVY:
	case SPRD_DRM_FORMAT_VYUY:
	case SPRD_DRM_FORMAT_NV12:
	case SPRD_DRM_FORMAT_NV21:
	case SPRD_DRM_FORMAT_NV16:
	case SPRD_DRM_FORMAT_NV61:
	case SPRD_DRM_FORMAT_YUV422:
	case SPRD_DRM_FORMAT_YVU422:
	case SPRD_DRM_FORMAT_YUV420:
	case SPRD_DRM_FORMAT_YVU420:
		return 2;
	default:
		return 1;
	}
}

u8 adf_format_vert_chroma_subsampling(u32 format)
{
	switch (format) {
	case SPRD_DRM_FORMAT_YUV410:
	case SPRD_DRM_FORMAT_YVU410:
		return 4;
	case SPRD_DRM_FORMAT_YUV420:
	case SPRD_DRM_FORMAT_YVU420:
	case SPRD_DRM_FORMAT_NV12:
	case SPRD_DRM_FORMAT_NV21:
		return 2;
	default:
		return 1;
	}
}
