/*
 *  <mipi_display.h> - <declaration of mipi dsi and dcs>
 *
 *  Copyright (C) 2019 Unisoc Communications Inc.
 *  History:
 *      <2021-08-09> <pony.wu@unisoc.com>
 *
 *      The above copyright notice shall be
 *      included in all copies or substantial portions of the Software.
 *
 *      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *      IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 *      CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 *      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 *      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MIPI_DISPLAY_H
#define MIPI_DISPLAY_H

/* MIPI DSI Processor-to-Peripheral transaction types */
enum {
	SPRD_MIPI_DSI_V_SYNC_START				= 0x01,
	SPRD_MIPI_DSI_V_SYNC_END				= 0x11,
	SPRD_MIPI_DSI_H_SYNC_START				= 0x21,
	SPRD_MIPI_DSI_H_SYNC_END				= 0x31,

	SPRD_MIPI_DSI_COLOR_MODE_OFF				= 0x02,
	SPRD_MIPI_DSI_COLOR_MODE_ON				= 0x12,
	SPRD_MIPI_DSI_SHUTDOWN_PERIPHERAL			= 0x22,
	SPRD_MIPI_DSI_TURN_ON_PERIPHERAL			= 0x32,

	SPRD_MIPI_DSI_GENERIC_SHORT_WRITE_0_PARAM		= 0x03,
	SPRD_MIPI_DSI_GENERIC_SHORT_WRITE_1_PARAM		= 0x13,
	SPRD_MIPI_DSI_GENERIC_SHORT_WRITE_2_PARAM		= 0x23,

	SPRD_MIPI_DSI_GENERIC_READ_REQUEST_0_PARAM		= 0x04,
	SPRD_MIPI_DSI_GENERIC_READ_REQUEST_1_PARAM		= 0x14,
	SPRD_MIPI_DSI_GENERIC_READ_REQUEST_2_PARAM		= 0x24,

	SPRD_MIPI_DSI_DCS_SHORT_WRITE			= 0x05,
	SPRD_MIPI_DSI_DCS_SHORT_WRITE_PARAM			= 0x15,

	SPRD_MIPI_DSI_DCS_READ				= 0x06,

	SPRD_MIPI_DSI_SET_MAXIMUM_RETURN_PACKET_SIZE		= 0x37,

	SPRD_MIPI_DSI_END_OF_TRANSMISSION			= 0x08,

	SPRD_MIPI_DSI_NULL_PACKET				= 0x09,
	SPRD_MIPI_DSI_BLANKING_PACKET			= 0x19,
	SPRD_MIPI_DSI_GENERIC_LONG_WRITE			= 0x29,
	SPRD_MIPI_DSI_DCS_LONG_WRITE				= 0x39,

	SPRD_MIPI_DSI_LOOSELY_PACKED_PIXEL_STREAM_YCBCR20	= 0x0c,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR24		= 0x1c,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR16		= 0x2c,

	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_30			= 0x0d,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_36			= 0x1d,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_YCBCR12		= 0x3d,

	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_16			= 0x0e,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_18			= 0x1e,
	SPRD_MIPI_DSI_PIXEL_STREAM_3BYTE_18			= 0x2e,
	SPRD_MIPI_DSI_PACKED_PIXEL_STREAM_24			= 0x3e,
};

/* SPRD_MIPI DSI Peripheral-to-Processor transaction types */
enum {
	SPRD_MIPI_DSI_RX_ACKNOWLEDGE_AND_ERROR_REPORT	= 0x02,
	SPRD_MIPI_DSI_RX_END_OF_TRANSMISSION			= 0x08,
	SPRD_MIPI_DSI_RX_GENERIC_SHORT_READ_RESPONSE_1BYTE	= 0x11,
	SPRD_MIPI_DSI_RX_GENERIC_SHORT_READ_RESPONSE_2BYTE	= 0x12,
	SPRD_MIPI_DSI_RX_GENERIC_LONG_READ_RESPONSE		= 0x1a,
	SPRD_MIPI_DSI_RX_DCS_LONG_READ_RESPONSE		= 0x1c,
	SPRD_MIPI_DSI_RX_DCS_SHORT_READ_RESPONSE_1BYTE	= 0x21,
	SPRD_MIPI_DSI_RX_DCS_SHORT_READ_RESPONSE_2BYTE	= 0x22,
};

/* SPRD_MIPI DCS commands */
enum {
	SPRD_MIPI_DCS_NOP			= 0x00,
	SPRD_MIPI_DCS_SOFT_RESET		= 0x01,
	SPRD_MIPI_DCS_GET_DISPLAY_ID		= 0x04,
	SPRD_MIPI_DCS_GET_RED_CHANNEL	= 0x06,
	SPRD_MIPI_DCS_GET_GREEN_CHANNEL	= 0x07,
	SPRD_MIPI_DCS_GET_BLUE_CHANNEL	= 0x08,
	SPRD_MIPI_DCS_GET_DISPLAY_STATUS	= 0x09,
	SPRD_MIPI_DCS_GET_POWER_MODE		= 0x0A,
	SPRD_MIPI_DCS_GET_ADDRESS_MODE	= 0x0B,
	SPRD_MIPI_DCS_GET_PIXEL_FORMAT	= 0x0C,
	SPRD_MIPI_DCS_GET_DISPLAY_MODE	= 0x0D,
	SPRD_MIPI_DCS_GET_SIGNAL_MODE	= 0x0E,
	SPRD_MIPI_DCS_GET_DIAGNOSTIC_RESULT	= 0x0F,
	SPRD_MIPI_DCS_ENTER_SLEEP_MODE	= 0x10,
	SPRD_MIPI_DCS_EXIT_SLEEP_MODE	= 0x11,
	SPRD_MIPI_DCS_ENTER_PARTIAL_MODE	= 0x12,
	SPRD_MIPI_DCS_ENTER_NORMAL_MODE	= 0x13,
	SPRD_MIPI_DCS_EXIT_INVERT_MODE	= 0x20,
	SPRD_MIPI_DCS_ENTER_INVERT_MODE	= 0x21,
	SPRD_MIPI_DCS_SET_GAMMA_CURVE	= 0x26,
	SPRD_MIPI_DCS_SET_DISPLAY_OFF	= 0x28,
	SPRD_MIPI_DCS_SET_DISPLAY_ON		= 0x29,
	SPRD_MIPI_DCS_SET_COLUMN_ADDRESS	= 0x2A,
	SPRD_MIPI_DCS_SET_PAGE_ADDRESS	= 0x2B,
	SPRD_MIPI_DCS_WRITE_MEMORY_START	= 0x2C,
	SPRD_MIPI_DCS_WRITE_LUT		= 0x2D,
	SPRD_MIPI_DCS_READ_MEMORY_START	= 0x2E,
	SPRD_MIPI_DCS_SET_PARTIAL_AREA	= 0x30,
	SPRD_MIPI_DCS_SET_SCROLL_AREA	= 0x33,
	SPRD_MIPI_DCS_SET_TEAR_OFF		= 0x34,
	SPRD_MIPI_DCS_SET_TEAR_ON		= 0x35,
	SPRD_MIPI_DCS_SET_ADDRESS_MODE	= 0x36,
	SPRD_MIPI_DCS_SET_SCROLL_START	= 0x37,
	SPRD_MIPI_DCS_EXIT_IDLE_MODE		= 0x38,
	SPRD_MIPI_DCS_ENTER_IDLE_MODE	= 0x39,
	SPRD_MIPI_DCS_SET_PIXEL_FORMAT	= 0x3A,
	SPRD_MIPI_DCS_WRITE_MEMORY_CONTINUE	= 0x3C,
	SPRD_MIPI_DCS_READ_MEMORY_CONTINUE	= 0x3E,
	SPRD_MIPI_DCS_SET_TEAR_SCANLINE	= 0x44,
	SPRD_MIPI_DCS_GET_SCANLINE		= 0x45,
	SPRD_MIPI_DCS_READ_DDB_START		= 0xA1,
	SPRD_MIPI_DCS_READ_DDB_CONTINUE	= 0xA8,
};

/* SPRD_MIPI DCS pixel formats */
#define SPRD_MIPI_DCS_PIXEL_FMT_24BIT	7
#define SPRD_MIPI_DCS_PIXEL_FMT_18BIT	6
#define SPRD_MIPI_DCS_PIXEL_FMT_16BIT	5
#define SPRD_MIPI_DCS_PIXEL_FMT_12BIT	3
#define SPRD_MIPI_DCS_PIXEL_FMT_8BIT		2
#define SPRD_MIPI_DCS_PIXEL_FMT_3BIT		1

#endif
