ifeq ($(strip $(CONFIG_NV_ENCRYPTION)),true)
EXTERNAL_DEFINES += NV_ENCRYPTION
endif

ifeq ($(strip $(BSP_CALIMODE_USE_BOOTIMG)),true)
EXTERNAL_DEFINES += SPRD_CALIMODE_USE_BOOTIMG=1
endif

ifneq ($(strip $(BSP_HWFEATURE)),)
EXTERNAL_DEFINES += CONFIG_BOOTLOADER_HWFEATURE='"$(strip $(BSP_HWFEATURE))"'
endif

ifeq ($(strip $(BSP_PRODUCT_SECURE_BOOT)),SPRD)
EXTERNAL_DEFINES += SPRD_SECBOOT
EXTERNAL_DEFINES += AVB_COMPILATION
EXTERNAL_DEFINES += PRODUCT_USE_DYNAMIC_PARTITIONS
#EXTERNAL_DEFINES += CONFIG_VERIFY_GPT

ifeq ($(strip $(BSP_SECURE_BOOT_KCE)),true)
EXTERNAL_DEFINES += CHIPRAM_KCE_FLAG
endif

ifeq ($(strip $(BSP_PKCS1_PSS_FLAG)),true)
EXTERNAL_DEFINES += PKCS1_PSS_FLAG
endif

ifeq ($(strip $(BSP_SHARKL5_CDSP_FLAG)),true)
EXTERNAL_DEFINES += SHARKL5_CDSP
endif

ifeq ($(strip $(BSP_NOT_VERIFY_MODEM_FLAG)),true)
EXTERNAL_DEFINES += NOT_VERIFY_MODEM
endif

ifeq ($(strip $(BSP_PROJECT_SEC_CM4_FLAG)),true)
EXTERNAL_DEFINES += PROJECT_SEC_CM4
endif

ifeq ($(strip $(BSP_SPRD_WCN_GNSS_FLAG)),true)
EXTERNAL_DEFINES += VERIFY_WCN_GNSS
endif

ifeq ($(strip $(BSP_SPRD_NV_LTE_FLAG)),true)
EXTERNAL_DEFINES += VERIFY_NV_LTE
endif

ifeq ($(strip $(BSP_KERNEL_VERSION)),kernel5.15)
EXTERNAL_DEFINES += SPRD_K515_FLAG
endif

ifeq ($(strip $(BSP_PRODUCT_VBOOT)),V2)
EXTERNAL_DEFINES += SPRD_VBOOT_V2
endif

ifeq ($(strip $(BSP_KCE_ENCRYPT_FLAG)),true)
EXTERNAL_DEFINES += KCE_ENCRYPT_FLAG
endif
endif #BSP_PRODUCT_SECURE_BOOT

ifeq ($(strip $(BSP_CONFIG_CHIP_UID)),true)
EXTERNAL_DEFINES += CONFIG_CHIP_UID
endif

ifeq ($(strip $(BSP_BOARD_TEE_CONFIG)),trusty)
EXTERNAL_DEFINES += TOS_TRUSTY
EXTERNAL_DEFINES += SPRD_TRUSTY_QL_TIPC
endif

ifeq ($(strip $(BSP_BOARD_REMOVE_SPRD_MODEM)),true)
EXTERNAL_DEFINES += CONFIG_REMOVE_MODEM
endif

ifeq ($(strip $(BSP_PRODUCT_DATA_ONLY)),true)
EXTERNAL_DEFINES += PRODUCT_SSMH_DATA_ONLY
endif

ifneq ($(strip $(BSP_PRODUCT_DISABLE_VAB)),true)
EXTERNAL_DEFINES += CONFIG_ANDROID_AB
endif

ifeq ($(BSP_PRODUCT_ENABLE_BOOTCONFIG),true)
ENABLE_BOOTCONFIG:=true
endif

ifneq ($(strip $(BSP_ANDROID_OS_VERSION)),)
EXTERNAL_DEFINES += CONFIG_ANDROID_OS_VERSION="$(strip $(BSP_ANDROID_OS_VERSION))"
endif

ifeq ($(strip $(BSP_BOARD_TEECFG_CUSTOM)),true)
EXTERNAL_DEFINES += CONFIG_TEECFG
EXTERNAL_DEFINES += TEECFG_MEM_ADDR=$(BSP_BOARD_TEECFG_MEM_ADDR)
endif

ifeq ($(strip $(BSP_LK_NV_SHA256)),true)
EXTERNAL_DEFINES += NV_CHECK_WITH_SHA256
endif

ifeq ($(strip $(CONFIG_FIXNV_SIGN)),true)
EXTERNAL_DEFINES += FIXNV_SIGN
endif

ifeq ($(strip $(BSP_NV_PROTECT_BACKUP)),true)
EXTERNAL_DEFINES += NV_PROTECT_BACKUP
endif
