/*
 * Copyright (C) 2016 Spreadtrum Communications Inc.
 */

#ifndef _UMP518_REG_BASE_H_
#define _UMP518_REG_BASE_H_

//#define SPRD_ADISLAVE_BASE	SPRD_ADISLAVE_PHYS
#define ANA_TIMER_BASE		(SPRD_ADISLAVE_BASE + 0x00)
#define ANA_WDG_BASE		(SPRD_ADISLAVE_BASE + 0x40)
#define ANA_INTC_BASE		(SPRD_ADISLAVE_BASE + 0x80)
/* #define ANA_CAL_BASE		(SPRD_ADISLAVE_BASE + 0xC0) */
#define ANA_AUD_BASE		(SPRD_ADISLAVE_BASE + 0x100)
#define ANA_BLTC_BASE		(SPRD_ADISLAVE_BASE + 0x180)
#define ANA_RTC_BASE		(SPRD_ADISLAVE_BASE + 0x200)
#define ANA_EIC_BASE		(SPRD_ADISLAVE_BASE + 0x280)
/* #define ANA_EFS_BASE		(SPRD_ADISLAVE_BASE + 0x300) */
#define ANA_TYPEC_BASE		(SPRD_ADISLAVE_BASE + 0x380)
#define ANA_FSCHG_BASE		(SPRD_ADISLAVE_BASE + 0x400)
#define ANA_PIN_BASE		(SPRD_ADISLAVE_BASE + 0x480)
#define ANA_ADC_BASE		(SPRD_ADISLAVE_BASE + 0x500)
#define ANA_PTEST_BASE		(SPRD_ADISLAVE_BASE + 0x600)
#define ANA_FGU_BASE		(SPRD_ADISLAVE_BASE + 0xC00)
#define ANA_PD_BASE		(SPRD_ADISLAVE_BASE + 0xE00)
#define ANA_AUDANA_BASE		(SPRD_ADISLAVE_BASE + 0x1000)
#define ANA_REGS_GLB_BASE	(SPRD_ADISLAVE_BASE + 0x1800)
#define ANA_EIC_DBNC_BASE	(SPRD_ADISLAVE_BASE + 0x2000)
#define ANA_EFS_BASE		(SPRD_ADISLAVE_BASE + 0x2100)

#define SPRD_ANA_EIC_PHYS	ANA_EIC_BASE
#define SPRD_ANA_GPIO_PHYS	0//do not have gpio module
#define ADC_BASE		ANA_ADC_BASE

#endif

